### ISSUE TITLE
iCub compatible compliation

### ISSUE THREAD

**Issue by iron76** [robotology-playground/kdl_codyco#26]
Within the iCub users, some people do not "make install". Binaries and include are copied by the default compilation config in the "current build" directory. The associated directory "bin" is added to the path. Include files are resolved thanks to the environment variable $ICUB_DIR. kdl_codyco and orocors_kdl are instead included thanks to the EXPORT_PACKAGE functionality of cmake. This second  option is not compatible with shared home-directories (currently used in certain iCub setup) and this poses issues to be solved if we want to maintain shared home-directories.

**Comment by traversaro** [comment]
This issue have been fixed in one of the hundreds of CMake bugfixes in [iDynTree library](https://github.com/robotology/idyntree).
